### PR TITLE
fixed bug

### LINKED ISSUE #27: bug: when delete icon is clicked, it ticks the checkbox
As the label is clickable, when you click the delete icon, it ticks the checkbox. Here is the [label code](https://github.com/the-collab-lab/tcl-44-smart-shopping-list/blob/a8e69a86d73c75930728a4b6d2b6500af7828504/src/components/ListItem.js#L107-L120).

This gif illustrates what happens when you click on the delete icon. 
delete-item

### PR DESCRIPTION
**Pull request by OloyedeTobi**
## Description

This PR fixes the bug with the delete button as pointed out by @hellodeborahuk 
- I added the `e.stopPropagation `method to the `deleteItems` function to prevent event propagation from child to parent component or vice versa.
- I wrapped the delete icon in a `button` tag to improve accessibility.

## Related Issue

closes #27 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓| :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

- From your terminal, pull down this branch with git pull origin `to-fix-delete-bug` and check that branch out with git checkout `to-fix-delete-bug`.
- Then npm start to launch the app.
- Click on the delete icon in front of any item to attempt deleting it.
- Observe if an unchecked checkbox is checked after clicking on the delete icon. 
CLICKING ON THE DELETE BUTTON SHOULD NOT CHECK OUT AN UNCHECKED CHECKBOX

### CODE REVIEW

File: src/components/ListItem.js [hunk 1]
```diff
@@ -114,10 +115,10 @@ const ListItem = ({ itemData }) => {
           onChange={handleChange}
         />
         <span> {itemData.itemName}</span>{' '}
-        <span className='deleteIconStyle'>
-        <VSCicons.VscTrash onClick={deleteItem}/>
-      </span>
       </label>
+      <button className='deleteIconStyle'>
+        <VSCicons.VscTrash onClick={deleteItem}/>
+      </button>
```
Comment (redapy) [inline src/components/ListItem.js]: Can you move the onClick to the button? it's a bad practice to add `eventListener` to an icon.

File: src/components/ListItem.js [hunk 2]
```diff
@@ -66,7 +66,8 @@ const ListItem = ({ itemData }) => {
 
 
   //Brings up a confirmation prompt before deleting the item, and if confirmed, deletes the item.
- const deleteItem = async() =>{
+ const deleteItem = async(e) =>{
+     e.stopPropagation()
```
Comment (redapy) [inline src/components/ListItem.js]: The bug was caused by the icon being inside a span. Now when we are using a button instead the bug does not exist anymore. so you can delete this `e.stopPropagation()`.

**Review by redapy — CHANGES_REQUESTED** [review]
Great job Tobi! I suggested some other changes

File: src/components/ListItem.js (hunk 2 above)
Comment (JimeBlue) [reply src/components/ListItem.js]: Great job @OloyedeTobi! I agree with Reda´s comments and have nothing further to add.

Comment (hellodeborahuk) [reply src/components/ListItem.js]: Great job Tobi! Ditto what Reda and Jimena have said.

File: src/components/ListItem.js (hunk 1 above)
Comment (OloyedeTobi) [reply src/components/ListItem.js]: oh! Thanks for that. I'll fix that

**Review by redapy — APPROVED** [review]
LGTM!
